matrix:
  include:
    - language: python
      python: 3.8
      install:
        - pip install pipenv
        - pipenv install
      script:
        - echo "done"
    - language: node_js
      node_js: 14.17.6
      script:
        - yarn run eslint
        - yarn run stylelint
        - yarn run styleguide:build
