matrix:
  include:
    - language: python
      python: 3.7
      install:
        - pip install pipenv
        - pipenv install
      script:
        - echo "done"
    - language: node_js
      node_js: 10.16.3
      script:
        - yarn run eslint
        - yarn run stylelint
        - yarn run styleguide:build
