matrix:
  include:
    - language: python
      python: 3.7
      install:
        - pip install pipenv
        - pipenv install
    - language: node_js
      node_js: 10.16.3
      before_install: cd src/frontend
      script:
        - yarn run eslint
        - yarn run stylelint
