# Generated by Django 3.2.7 on 2021-12-26 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_item', models.IntegerField(null=True)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.CharField(max_length=200)),
                ('request_out', models.DateTimeField()),
                ('request_in', models.DateTimeField()),
                ('actual_out', models.DateTimeField(blank=True, null=True)),
                ('actual_in', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Signed Out', 'Signedout'), ('Returned', 'Returned')], default='Requested', max_length=10)),
                ('approving_board_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_approvals', to=settings.AUTH_USER_MODEL)),
                ('equipment_instances', models.ManyToManyField(blank=True, related_name='linked_requests', to='api.EquipmentInstance')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('equipment_category_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_types', to='api.equipmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRequestItemQty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipmentitem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipmentrequest')),
            ],
            options={
                'unique_together': {('request', 'item')},
            },
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='equipment_items',
            field=models.ManyToManyField(through='api.EquipmentRequestItemQty', to='api.EquipmentItem'),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='equipment_type_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_items', to='api.equipmenttype'),
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='equipment_item_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_instances', to='api.equipmentitem'),
        ),
    ]
