# Generated by Django 3.1.2 on 2020-10-28 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('api', '0001_initial'), ('api', '0002_equipmentitem_id_of_type'), ('api', '0003_auto_20200322_0139'), ('api', '0004_auto_20200323_0355'), ('api', '0005_auto_20200324_0016'), ('api', '0006_equipmentrequest_user'), ('api', '0007_auto_20200411_2111'), ('api', '0008_auto_20201028_2049')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('product_url', models.URLField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_types', to='api.equipmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(editable=False)),
                ('equipment_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_items', to='api.equipmenttype')),
                ('id_of_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_in', models.DateTimeField(null=True)),
                ('request_out', models.DateTimeField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('equipment_items', models.ManyToManyField(related_name='linked_requests', to='api.EquipmentItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requests', to=settings.AUTH_USER_MODEL)),
                ('actual_in', models.DateTimeField(blank=True, null=True)),
                ('actual_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Signed Out', 'Signedout'), ('Returned', 'Returned')], default='Requested', max_length=10)),
            ],
        ),
    ]
