# Generated by Django 4.0a1 on 2021-10-15 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_of_item', models.IntegerField(null=True)),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('equipment_category_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_types', to='api.equipmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('request_out', models.DateTimeField(null=True)),
                ('request_in', models.DateTimeField(null=True)),
                ('actual_out', models.DateTimeField(blank=True, null=True)),
                ('actual_in', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('Signed Out', 'Signedout'), ('Returned', 'Returned')], default='Requested', max_length=10)),
                ('equipment_items', models.ManyToManyField(related_name='linked_requests', to='api.EquipmentInstance')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requests', to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('product_url', models.URLField(blank=True)),
                ('equipment_type_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_items', to='api.equipmenttype')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='equipment_item_FK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_instances', to='api.equipmentitem'),
        ),
    ]
