# Generated by Django 3.0.3 on 2020-03-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentitem',
            name='id_of_type',
            field=models.IntegerField(null=True),
        ),
    ]
