# Generated by Django 3.2.7 on 2021-12-24 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='approving_board_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='linked_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='equipment_instances',
            field=models.ManyToManyField(
                related_name='linked_requests', to='api.EquipmentInstance'),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='project',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentRequestItemQty',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.equipmentitem')),
                ('request', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.equipmentrequest')),
            ],
            options={
                'unique_together': {('request', 'item')},
            },
        ),
        migrations.RemoveField(
            model_name='equipmentrequest',
            name='equipment_items',
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='equipment_items',
            field=models.ManyToManyField(
                through='api.EquipmentRequestItemQty', to='api.EquipmentItem'),
        ),
    ]
