# Generated by Django 2.2.5 on 2019-10-29 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitem',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='equipmentitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='equipmentitem',
            table='Equipment Items',
        ),
    ]
