# Generated by Django 2.2.5 on 2019-10-29 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191029_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentitem',
            options={},
        ),
        migrations.AlterModelTable(
            name='equipmentitem',
            table=None,
        ),
    ]
