# Generated by Django 3.0.3 on 2020-03-22 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_equipmentitem_id_of_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentrequest',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='equipmentrequest',
            name='start_date',
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='equipment_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_requests', to='api.EquipmentItem'),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='request_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='request_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
