# Generated by Django 3.2.7 on 2021-12-24 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20211224_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='approving_board_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
