# Generated by Django 3.0.3 on 2020-03-23 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200322_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentrequest',
            name='equipment_item',
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='equipment_item',
            field=models.ManyToManyField(related_name='linked_requests', to='api.EquipmentItem'),
        ),
    ]
