# Generated by Django 3.0.3 on 2020-03-24 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200323_0355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentrequest',
            old_name='equipment_item',
            new_name='equipment_items',
        ),
    ]
