# Generated by Django 3.2.7 on 2021-12-25 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_equipmentrequest_approving_board_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentrequest',
            name='project',
            field=models.CharField(default="Test", max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_out',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='timestamp',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
