# Generated by Django 3.0.3 on 2020-04-11 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_equipmentrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentrequest',
            name='actual_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='actual_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentrequest',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Signed Out', 'Signedout'), ('Returned', 'Returned')], default='Requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='request_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='equipmentrequest',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
