export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_QTY = 'ADJUST_QTY';
export const SET_CHECKOUT_TIME = 'SET_CHECKOUT_TIME';
export const SET_RETURN_TIME = 'SET_RETURN_TIME';
