# Generated by Django 2.2.5 on 2019-10-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191029_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentitem',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
